### ISSUE TITLE
Add a Todo page

### ISSUE THREAD

**Issue by Issa92optimus** [Issa92optimus/Task_app#4]
The Todo page must contain:

- [ ] List of all todos
- [ ] Add Todo button
- [ ] Update Todo button
- [ ] Delete Todo button
